[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://relay-v5ne.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/onboarding"
  to = "/onboarding.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/login.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://getrelay-app.netlify.app"
    Access-Control-Allow-Credentials = "true"
